app:
  # 运行模式【debug、release】
  mode:        "release"
  # 运行地址【不懂请写: 0.0.0.0】
  address:     "0.0.0.0"
  # 运行端口
  port:        1500

# 以下内容如果不懂, 请不要修改

# JWT配置
jwt:
  # 过期时间, 单位：天
  expires-time: 30
  # 缓冲时间, 单位：天
  buffer-time: 31